# Generated by Django 3.1.3 on 2023-01-15 05:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=150)),
                ('blog_title', models.CharField(max_length=500)),
                ('blog_image_one', models.ImageField(blank=True, null=True, upload_to='uploaded_blog_images/')),
                ('blog_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('blog_author', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_phone', models.CharField(max_length=50)),
                ('company_optional_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(default='', max_length=254)),
                ('company_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('category_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='uploaded_category_image/')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_descriptions', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='SEO_META',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SEO META',
                'verbose_name_plural': 'SEO METAS',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=150)),
                ('product_image_front', models.ImageField(upload_to='uploaded_product_images/')),
                ('product_image_back', models.ImageField(blank=True, null=True, upload_to='uploaded_product_images/')),
                ('product_image_left', models.ImageField(blank=True, null=True, upload_to='uploaded_product_images/')),
                ('product_image_right', models.ImageField(blank=True, null=True, upload_to='uploaded_product_images/')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(default='', max_length=100)),
                ('product_price_dollar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_fabric', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=100)),
                ('product_weight', models.CharField(max_length=50)),
                ('product_color', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.TextField()),
                ('product_available_sizes', models.CharField(blank=True, max_length=200, null=True)),
                ('product_blog_url', models.CharField(blank=True, max_length=500, null=True)),
                ('product_yarn_count', models.CharField(blank=True, max_length=50, null=True)),
                ('product_yarn_ply', models.CharField(blank=True, max_length=50, null=True)),
                ('product_style', models.CharField(blank=True, max_length=50, null=True)),
                ('product_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('product_knit_guage', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rita_cashmere.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rita_cashmere.product')),
            ],
        ),
    ]
