# Generated by Django 3.1.3 on 2023-01-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rita_cashmere', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='CompanyInfo',
        ),
    ]
