# Generated by Django 3.1.3 on 2023-01-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rita_cashmere', '0002_auto_20230115_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
