# Generated by Django 3.1.3 on 2023-01-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rita_cashmere', '0005_auto_20230121_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image_one_alt',
            field=models.CharField(default='rita-cashmere', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='about_image_three_alt',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='about_image_two_alt',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
