# Generated by Django 3.1.3 on 2023-01-21 07:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rita_cashmere', '0006_auto_20230121_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text_one',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text_three',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text_two',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
