# Generated by Django 3.1.3 on 2023-01-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rita_cashmere', '0008_auto_20230121_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_image_one',
            new_name='blog_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_image_alt',
            field=models.CharField(default='rita cashmere industries best known for knitted products', max_length=150),
        ),
    ]
