# Generated by Django 3.1.3 on 2023-01-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rita_cashmere', '0009_auto_20230121_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='uploaded_carousel_image/')),
                ('image_one_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='uploaded_carousel_image/')),
                ('image_two_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='uploaded_carousel_image/')),
                ('image_three_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='uploaded_carousel_image/')),
                ('image_four_alt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
